# Generated by Django 5.2.6 on 2025-09-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='Código de Estudiante')),
                ('career', models.CharField(choices=[('sistemas', 'Sistemas de Información'), ('software', 'Desarrollo de Software'), ('redes', 'Redes y Comunicaciones'), ('industrial', 'Ingeniería Industrial'), ('mecanica', 'Ingeniería Mecánica')], max_length=20, verbose_name='Carrera')),
                ('semester', models.IntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre'), (3, 'Tercer Semestre'), (4, 'Cuarto Semestre'), (5, 'Quinto Semestre'), (6, 'Sexto Semestre')], verbose_name='Semestre')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
